# Generated by Django 4.2.3 on 2023-08-05 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cat_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pr_name", models.CharField(max_length=100)),
                ("pr_cost", models.IntegerField(default=0)),
                ("pr_discount", models.IntegerField(default=0)),
                ("pr_discost", models.IntegerField(null=True)),
                ("pr_brand", models.CharField(max_length=100, null=True)),
                ("pr_rating", models.IntegerField(null=True)),
                ("pr_colour", models.CharField(max_length=50, null=True)),
                ("pr_description", models.CharField(max_length=250, null=True)),
                ("manufacture_date", models.DateField(null=True)),
                ("pr_mimage", models.ImageField(null=True, upload_to="image/")),
                ("pr_simage1", models.ImageField(null=True, upload_to="image/")),
                ("pr_simage2", models.ImageField(null=True, upload_to="image/")),
                ("pr_simage3", models.ImageField(null=True, upload_to="image/")),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ecommerce_app.categorymodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_age", models.IntegerField()),
                ("user_dob", models.DateField()),
                ("user_gender", models.CharField(max_length=10)),
                ("user_addr", models.CharField(max_length=100)),
                ("user_phno", models.IntegerField()),
                ("photo", models.ImageField(null=True, upload_to="image/")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce_app.productmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce_app.customermodel",
                    ),
                ),
            ],
        ),
    ]
