# Generated by Django 4.2.3 on 2023-08-05 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ecommerce_app.categorymodel",
            ),
        ),
    ]
