from . import views
from django.urls import path

urlpatterns = [
    path("", views.load_home, name="load_home"),
    path("home/", views.load_home_al, name="load_home_al"),
    path("login/", views.load_login, name="load_login"),
    path("signup/", views.load_signup, name="load_signup"),
    path("usercreate/", views.usercreate, name="usercreate"),
    path("userlogin/", views.userlogin, name="userlogin"),
    path('menu/',views.load_menu,name="load_menu"),
    path("product/", views.load_product, name="load_product"),
    path("createproduct/", views.productcreate, name="productcreate"),
    path("category/", views.load_category, name="load_category"),
    path("createcategory/", views.categorycreate, name="categorycreate"),
    path("productdetailsfh/<int:pk>/", views.load_product_details_fh, name="load_product_details_fh"),
    path("productdetailsfp/<int:pk>/", views.load_product_details_fp, name="load_product_details_fp"),
    path("showcategory",views.show_category,name="show_category"),
    path("loadcategoryupdate/<int:pk>", views.load_category_update, name="load_category_update"),
    path("updatecategory/<int:pk>", views.updatecategory, name="updatecategory"),
    path("deletecategory/<int:pk>", views.deletecategory, name="deletecategory"),
    path("deleteproduct/<int:pk>", views.deleteproduct, name="deleteproduct"),
    path("deleteuser/<int:pk>", views.deleteuser, name="deleteuser"),
    path("deletecart/<int:pk>", views.deletecart, name="deletecart"),
    path("cart/",views.load_cart,name="load_cart"),
    path("addtocart/<int:pk>",views.add_to_cart,name="add_to_cart"),
    path("cart/",views.load_cart,name="load_cart"),
    path("addtocart/<int:pk>",views.add_to_cart,name="add_to_cart"),
    path("order/",views.load_order,name="load_order"),
    path("shop/<int:pk>",views.load_shop,name="load_shop"),
    path("load_show_products/",views.load_show_products,name="load_show_products"),
    path("construction/",views.load_construction,name="load_construction"),
    path("admin_product_details/<int:pk>",views.admin_product_details,name="admin_product_details"),
    path("load_show_user/",views.load_show_user,name="load_show_user"),
    path("load_user_details/<int:pk>",views.load_user_details,name="load_user_details"),
    path("load_edit_product/<int:pk>",views.load_edit_product,name="load_edit_product"),
    path("edit_product/<int:pk>",views.edit_product,name="edit_product"),
    path("load_edit_user/<int:pk>",views.load_edit_user,name="load_edit_user"),
    path("edit_user/<int:pk>",views.edit_user,name="edit_user"),
    path("load_home_user_details/<int:pk>",views.load_home_user_details,name="load_home_user_details"),
    path("logout/",views.logout,name="logout")
]